# Installs Valkey or Redis engine from source. Assumes Ubuntu 20.04 or later.
name: Install Engine
description: |
  Installs Valkey or Redis engine from source. Assumes Ubuntu 20.04 or later.
  The engine is built with TLS support enabled.

inputs:
  engine-type:
    description: "Engine type - valkey or redis"
    type: string
    required: true
    options:
      - valkey
      - redis
  engine-tag:
    description: "Git tag on engine source repository"
    type: string
    required: true

runs:
  using: "composite"

  steps:
    - uses: actions/cache@v4
      id: cache-engine
      with:
        path: |
          # NOTE: assumes that the engine is installed in /usr/local/bin
            /usr/local/bin/"${{ inputs.engine-type }}"-server
            /usr/local/bin/"${{ inputs.engine-type }}"-cli
        key: engine-${{ inputs.engine-type }}-${{ inputs.engine-tag }}

    - name: Prepare engine sources
      if: ${{ steps.cache-engine.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        if [[ "${{ inputs.engine-type }}" == "valkey" ]]; then
            ENGINE_REPO_URL="https://github.com/valkey-io/valkey.git"
        elif [[ "${{ inputs.engine-type }}" == "redis" ]]; then
            ENGINE_REPO_URL="https://github.com/redis/redis.git"
        else
            echo "Unknown engine-type: ${{ inputs.engine-type }}"
            exit 1
        fi

        if [[ -d engine ]]; then
            echo "Removing existing engine directory..."
            rm -fR engine
        fi

        echo "Cloning $ENGINE_REPO_URL and checking out tag ${{ inputs.engine-tag }}..."
        git clone "$ENGINE_REPO_URL" engine
        cd engine
        git checkout tags/"${{ inputs.engine-tag }}"

    - name: Build and install engine
      if: ${{ steps.cache-engine.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        cd engine
        make -j2 BUILD_TLS=yes install
